### ISSUE TITLE
Adding Plain text field break categories view

### ISSUE THREAD

**Issue by migmake** [mmikkel/DashCols-Craft#20] opened 2015-08-13 12:43 UTC
Got an error when adding PLAIN TEXT field to CATEGORIES view
![screen shot 2015-08-13 at 05 43 04](https://cloud.githubusercontent.com/assets/3531623/9249939/313d48ac-417e-11e5-87e0-a01b17c0d480.jpg)

**Comment by mmikkel** [comment] 2015-08-21 09:06
Thanks for the report, @migswd. I'll look at it ASAP.

**Comment by mmikkel** [comment] 2015-09-08 07:12
Hello @migswd – sorry for the late follow-up. Unfortunately, I'm not able to reproduce your issue (see http://cly.mmikkel.no/image/3R2g3S0r1Z0D), so I'm closing it for now. I have a couple of questions for you:
1. Are you still experiencing the problem?
2. Have you checked your logs (the issue might not be related to DashCols)? The logs are found under /craft/storage/runtime/logs.

If possible, you can send me a full SQL dump of your site, and I'll look into the issue further. You can also zip the /logs directory and send me that.

I'll reopen the issue if/when I hear back from you and can confirm that this is indeed an issue w/ DashCols.

**Closed as completed by mmikkel** 2015-09-08 07:12 UTC
Labels: bug
